#!/bin/bash

# Define a timestamp function
timestamp() {
  date +"%D%M%Y-%T"
}
scp -r -oHostKeyAlgorithms=+ssh-dss pmangala@scci71752.sc.intel.com:/nfs/site/disks/infra_work_05/pmangala/ATLAS/* ~/Documents/GitHub/ATLAS/
git add .
ts=`timestamp`
message="Commit at $ts"
echo "$message"
echo "HELLO"
git commit -a -m "$message"
git push
